# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pedidos.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'pedidos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpedidos.proto\"\xbb\x01\n\rPedidoRequest\x12\x17\n\x0fnombre_producto\x18\x01 \x01(\t\x12\x0e\n\x06precio\x18\x02 \x01(\x02\x12\x15\n\rpasarela_pago\x18\x03 \x01(\t\x12\x15\n\rmarca_tarjeta\x18\x04 \x01(\t\x12\r\n\x05\x62\x61nco\x18\x05 \x01(\t\x12\x14\n\x0cregion_envio\x18\x06 \x01(\t\x12\x17\n\x0f\x64ireccion_envio\x18\x07 \x01(\t\x12\x15\n\remail_cliente\x18\x08 \x01(\t\"!\n\x0ePedidoResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2<\n\x07Pedidos\x12\x31\n\x0eRealizarPedido\x12\x0e.PedidoRequest\x1a\x0f.PedidoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pedidos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PEDIDOREQUEST']._serialized_start=18
  _globals['_PEDIDOREQUEST']._serialized_end=205
  _globals['_PEDIDORESPONSE']._serialized_start=207
  _globals['_PEDIDORESPONSE']._serialized_end=240
  _globals['_PEDIDOS']._serialized_start=242
  _globals['_PEDIDOS']._serialized_end=302
# @@protoc_insertion_point(module_scope)
